name: Front

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Authorize Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t kawwik/tutor-project-messenger-front -f Dockerfile .
      - name: Push to Docker Hub
        run: docker push kawwik/tutor-project-messenger-front
